# Redisson配置文件
singleServerConfig:
  address: "redis://localhost:6379"
  database: 0
  connectionPoolSize: 10
  connectionMinimumIdleSize: 5
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: "subtitle-fusion"

threads: 16
nettyThreads: 32

# 编解码器
codec: !<org.redisson.codec.JsonJacksonCodec> {}

# 传输模式
transportMode: "NIO"
